# Site settings
title: Divya Portfolio
email: divrk05@yahoo.com 
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

github_username: divramakrishnan

# Build settings
markdown: kramdown

theme: jekyll-theme-hacker